backend:
  name: github
  repo: Jephuff/certified-pest-control
  branch: master
media_folder: img/uploads
collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: data/home.json
        description: Home Page Content
        preview: false
        fields:
          - name: questions
            label: Common Questions
            description: Top 2 questions will be displayed
            widget: list
            fields:
              - label: Question
                name: question
                widget: string
              - label: Answer
                name: answer
                widget: string
          - label: Why Choose Us
            name: why
            widget: object
            fields:
              - name: reasons
                label: Reasons
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: selectImage
                    options:
                      - value: links/experience.png
                        label: Experience
                      - value: links/personal.png
                        label: Personal
                      - value: links/competitive.png
                        label: Competitive
                  - label: Title Color
                    name: color
                    widget: select
                    options:
                      - green
                      - yellow
                      - orange
                  - label: Title
                    name: title
                    widget: string
                  - label: Detail
                    name: detail
                    widget: string
          - name: services
            label: Services
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Detail
                name: detail
                widget: string
      - name: contact
        label: Contact Page
        file: data/contact.json
        description: Contact Page Content
        preview: false
        fields:
          - label: Phone Number
            name: phone
            widget: string
      - name: services
        label: Services Page
        file: data/services.json
        description: Services Page Content
        preview: false
        fields:
          - name: addOns
            label: Add Ons
            description: available add-ons
            widget: list
            fields:
              - label: Add On
                name: addOn
                widget: string
