backend:
  name: github
  repo: Jephuff/certified-pest-control
  branch: master

media_folder: "img/uploads"

collections:
  - name: "homepage"
    label: "Home Page"
    folder: "data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}