backend:
  name: github
  repo: Jephuff/certified-pest-control
  branch: master

media_folder: "img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "data/home.json"
        description: "Home Page Content"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - name: "contact"
        label: "Contact Page"
        file: "data/contact.json"
        description: "Contact Page Content"
        fields:
          - {label: "Title", name: "title", widget: "string"}