backend:
  name: github
  repo: Jephuff/certified-pest-control
  branch: master

media_folder: "img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "data/pages"
    create: true
    format: "json"
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}