backend:
  name: github
  repo: Jephuff/certified-pest-control
  branch: master

media_folder: "img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "data/home.json"
        description: "Home Page Content"
        preview: false
        fields:
          - name: "questions"
            label: "Common Questions"
            description: "Top 2 questions will be displayed"
            widget: list
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "string"}
      - name: "contact"
        label: "Contact Page"
        file: "data/contact.json"
        description: "Contact Page Content"
        preview: false
        fields:
          - {label: "Phone Number", name: "phone", widget: "string"}
      - name: "services"
        label: "Services Page"
        file: "data/services.json"
        description: "Services Page Content"
        preview: false
        fields:
          - name: "addOns"
            label: "Add Ons"
            description: "available add-ons"
            widget: list
            fields:
              - {label: "Add On", name: "addOn", widget: "string"}